language: ruby
bundler_args: --without debug
script: "bundle exec rspec spec"
sudo: false
cache: bundler
rvm:
 - 2.1
 - 2.2.4
 - 2.3.1
 - jruby-9.0.4.0
 - rbx
matrix:
  allow_failures:
      - rvm: jruby-9.0.4.0
      - rvm: rbx
